package activityreport.report;

import activityreport.model.Activity;

import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.stream.Collectors;

/**
 * Simple markdown report generator (fallback when AI is disabled)
 */
public class MarkdownReportGenerator {

    public static String generateSimple(List<Activity> activities, Instant startDate, Instant endDate) {
        StringBuilder report = new StringBuilder();

        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
            .withZone(ZoneId.systemDefault());
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")
            .withZone(ZoneId.systemDefault());

        // Header
        report.append("# Activity Report\n\n");
        report.append(String.format("**Period:** %s to %s\n\n",
            dateFormatter.format(startDate),
            dateFormatter.format(endDate)));
        report.append(String.format("**Total Activities:** %d\n\n", activities.size()));

        // Sort activities by timestamp (most recent first)
        List<Activity> sortedActivities = new ArrayList<>(activities);
        sortedActivities.sort(Comparator.comparing(Activity::timestamp).reversed());

        // Group by source
        Map<String, List<Activity>> bySource = sortedActivities.stream()
            .collect(Collectors.groupingBy(Activity::source, LinkedHashMap::new, Collectors.toList()));

        // Generate report sections by source
        for (Map.Entry<String, List<Activity>> entry : bySource.entrySet()) {
            String source = entry.getKey();
            List<Activity> sourceActivities = entry.getValue();

            report.append(String.format("## %s (%d activities)\n\n", source, sourceActivities.size()));

            // Further group by type within source
            Map<String, List<Activity>> byType = sourceActivities.stream()
                .collect(Collectors.groupingBy(Activity::type, LinkedHashMap::new, Collectors.toList()));

            for (Map.Entry<String, List<Activity>> typeEntry : byType.entrySet()) {
                String type = typeEntry.getKey();
                List<Activity> typeActivities = typeEntry.getValue();

                report.append(String.format("### %s (%d)\n\n", capitalizeFirst(type), typeActivities.size()));

                for (Activity activity : typeActivities) {
                    report.append(String.format("- **[%s]** ",
                        dateTimeFormatter.format(activity.timestamp())));

                    if (activity.url() != null && !activity.url().isEmpty()) {
                        report.append(String.format("[%s](%s)",
                            activity.title(), activity.url()));
                    } else {
                        report.append(activity.title());
                    }

                    if (activity.description() != null && !activity.description().isEmpty()) {
                        String desc = activity.description();
                        // Truncate long descriptions
                        if (desc.length() > 150) {
                            desc = desc.substring(0, 150) + "...";
                        }
                        // Escape newlines
                        desc = desc.replace("\n", " ");
                        report.append("\n  - ").append(desc);
                    }

                    report.append("\n");
                }

                report.append("\n");
            }
        }

        report.append("---\n\n");
        report.append("*Generated by activity-report*\n");

        return report.toString();
    }

    private static String capitalizeFirst(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1).replace("_", " ");
    }
}
